json.id user[:id]
json.username user[:username]
json.avatar user[:avatar] if user[:avatar]
json.type user[:type] if user[:type]
json.email user[:email] if user[:email]
json.age user[:age] if user[:age]
json.gender user[:gender] if user[:gender]
json.school_id user[:school_id] if user[:school_id]
json.school user[:school] if user[:school]