json.id user[:id]
json.username user[:username]
json.email user[:email] if user[:email]
json.first_name user[:first_name] if user[:first_name]
json.last_name user[:last_name] if user[:last_name]
json.age user[:age] if user[:age]
json.gender user[:gender] if user[:gender]
json.friends user[:friends] if user[:friends]