# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4845d6d959bdbcf7b4a6978e0f78f321b4e4a24b86d31b65190814762d22d895b40b45ea10ed68972d217dd86f3d28dd0792c920cd5ece1d711c0a53bf734d42

test:
  secret_key_base: fb79be4ea7922358967904f68d745dc81da49f3b7c3d6176aab3390b6b295db8f83f7113cc407e6b93cf25d71567ad2aa9604e36d3464693a467af5e0e2ee111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
