json.id score[:id]
json.owner_id score[:owner_id] if score[:owner_id]
json.owner_type score[:owner_type] if score[:owner_type]
json.user_id score[:user_id] if score[:user_id]
json.scorer_id score[:scorer_id] if score[:scorer_id]
json.comment score[:comment] if score[:comment]
json.score score[:score] if score[:score]