json.id school[:id]
json.name school[:name]
json.region_id school[:region_id] if school[:region_id]
json.country_id school[:country_id] if school[:country_id]
json.province_id school[:province_id] if school[:province_id]
json.city_id school[:city_id] if school[:city_id]
json.district_id school[:district_id] if school[:district_id]
json.user_id school[:user_id] if school[:user_id]
json.master_id school[:master_id] if school[:master_id]