json.id school[:id]
json.name school[:name]
json.region_id school[:region_id]
json.country_id school[:country_id]
json.province_id school[:province_id]
json.city_id school[:city_id]
json.district_id school[:district_id]